CANTIDAD_INGRESO_LOGS=100

LONGITUD_MINIMA_DESCRIPCION=5
LONGITUD_MAXIMA_DESCRIPCION=150

OBSERVACION_RODELA_MIN=5
OBSERVACION_RODELA_MAX=150

CANTIDAD_INGRESO_PRODUCTO_TERMINADO=100
CANTIDAD_CORRECCION_PRODUCTO_TERMINADO=50
CANTIDAD_AJUSTE_PRODUCTO_TERMINADO=500

DIAS_MAXIMOS_REPORTE_PRODUCCION=366

LONGITUD_MINIMA_NOMBRE_TIPO_BOBINA = 3
LONGITUD_MAXIMA_NOMBRE_TIPO_BOBINA = 30
DIAMETRO_MAXIMO_MM = 5000
FORMATO_MAXIMO_MM = 5000
TARA_MAXIMA_KG = 500
CREPADO_MAXIMO_PORCENTAJE = 100
RESISTENCIA_MAXIMA_KGF = 1000

LONGITUD_MINIMA_NOMBRE_LINEA = 3
LONGITUD_MAXIMA_NOMBRE_LINEA = 30
CANTIDAD_MINIMA_ROLLOS = 2
CANTIDAD_MAXIMA_ROLLOS = 100
CANTIDAD_MINIMA_UNIDADES = 20
CANTIDAD_MAXIMA_UNIDADES = 1000
CANTIDAD_MAXIMA_POR_UNIDAD_TERMINADA = 50
