ESTADO_MATERIA_PRIMA_EN_ALMACEN = 1

ESTADO_PRODUCCION_EN_PRODUCCION = 1
ESTADO_PRODUCCION_PAUSA = 2
ESTADO_PRODUCCION_FINALIZADO = 3
ESTADO_PRODUCCION_CANCELADA = 4
ESTADO_PRODUCCION_CAMBIO_LINEA = 5

ESTADO_USUARIO_ACTIVO = 1
ESTADO_USUARIO_INACTIVO = 2
ESTADO_USUARIO_SUSPENDIDO = 3

TRANSICIONES_ESTADO_USUARIO = {
    ESTADO_USUARIO_ACTIVO: {ESTADO_USUARIO_INACTIVO, ESTADO_USUARIO_SUSPENDIDO},
    ESTADO_USUARIO_INACTIVO: {ESTADO_USUARIO_ACTIVO, ESTADO_USUARIO_SUSPENDIDO},
    ESTADO_USUARIO_SUSPENDIDO: set(),
}
