[project]
name = "blanquita-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "argon2-cffi>=25.1.0",
    "dotenv>=0.9.9",
    "fastapi>=0.138.1",
    "httpx>=0.28.1",
    "psycopg2-binary>=2.9.12",
    "pydantic>=2.13.4",
    "pyjwt[crypto]>=2.13.0",
    "reportlab>=5.0.0",
    "segno>=1.6.6",
    "slowapi>=0.1.10",
    "sqlalchemy>=2.0.51",
    "supabase>=2.31.0",
    "tzdata>=2026.3",
    "uvicorn>=0.49.0",
]
